modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Mrbysco/Oreberries-Replanted"
license="MIT"

[[mods]]
modId="oreberriesreplanted"
version="${file.jarVersion}"
displayName="Oreberries Replanted"
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted"
authors="Mrbysco, ShyNieke"
description='''
Bringing back the Ore berries idea from Tinkers' 1.7.10 to recent minecraft
'''
[[dependencies.oreberriesreplanted]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.oreberriesreplanted]]
modId="forge"
mandatory=true
versionRange="[36.2.5,37)"
ordering="NONE"
side="BOTH"