modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/Oreberries-Replanted"
license="MIT"

[[mods]]
modId="oreberriesreplanted"
version="${file.jarVersion}"
displayName="Oreberries Replanted"
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted"
authors="Mrbysco, ShyNieke"
description='''
Bringing back the Ore berries idea from Tinkers' 1.7.10 to recent minecraft
'''